#!/bin/bash
# QC and Trimming Pipeline
# Author: Abaysew


# ------------------------------
# USER INPUT
# ------------------------------
RAW_DIR="raw_data/mtb"                   < update based on your path
SAMPLE="ERR15418593"                     < update based on your sample id 
TRIM_ADAPTERS="adapters/adapter.fa"      < update based on your path
THREADS=4
# ------------------------------

echo "Counting reads in $RAW_DIR/${SAMPLE}_1.fastq.gz..."
echo $(( $(zcat "$RAW_DIR/${SAMPLE}_1.fastq.gz" | wc -l) / 4 ))

# Create output directories
mkdir -p qc_raw/mtb/fastqc
mkdir -p qc_trim/mtb/fastp
mkdir -p qc_trim/mtb/trimmomatic
mkdir -p trimmed/mtb/fastp
mkdir -p trimmed/mtb/trimmomatic
mkdir -p qc_trim/mtb/fastp_report
mkdir -p trimmed/mtb/trimmomatic_report

# ------------------------------
# RAW QC
# ------------------------------
echo "Running FastQC on raw reads..."
fastqc "$RAW_DIR/${SAMPLE}_1.fastq.gz" "$RAW_DIR/${SAMPLE}_2.fastq.gz" -o qc_raw/mtb/fastqc

echo "Running MultiQC..."
multiqc qc_raw/mtb/fastqc -o qc_raw/mtb/fastqc

# ------------------------------
# FASTP TRIMMING
# ------------------------------
echo "Running fastp..."
fastp \
  -i "$RAW_DIR/${SAMPLE}_1.fastq.gz" \
  -I "$RAW_DIR/${SAMPLE}_2.fastq.gz" \
  -l 30 \
  --cut_front --cut_tail \
  -W 4 -M 20 \
  --detect_adapter_for_pe \
  -w $THREADS \
  -o trimmed/mtb/fastp/${SAMPLE}_R1.trimmed.fastq.gz \
  -O trimmed/mtb/fastp/${SAMPLE}_R2.trimmed.fastq.gz \
  --html qc_trim/mtb/fastp_report/${SAMPLE}.fastp.html \
  --json qc_trim/mtb/fastp_report/${SAMPLE}.fastp.json

echo "FastQC after fastp..."
fastqc trimmed/mtb/fastp/${SAMPLE}_R*.trimmed.fastq.gz -o qc_trim/mtb/fastp
multiqc qc_trim/mtb/fastp -o qc_trim/mtb/fastp

# ------------------------------
# TRIMMOMATIC
# ------------------------------
echo "Running Trimmomatic..."

trimmomatic PE \
  -threads $THREADS \
  -phred33 \
  -summary trimmed/mtb/trimmomatic_report/${SAMPLE}_trimmomatic_stats.txt \
  "$RAW_DIR/${SAMPLE}_1.fastq.gz" \
  "$RAW_DIR/${SAMPLE}_2.fastq.gz" \
  trimmed/mtb/trimmomatic/${SAMPLE}_R1_paired.fastq.gz \
  trimmed/mtb/trimmomatic/${SAMPLE}_R1_unpaired.fastq.gz \
  trimmed/mtb/trimmomatic/${SAMPLE}_R2_paired.fastq.gz \
  trimmed/mtb/trimmomatic/${SAMPLE}_R2_unpaired.fastq.gz \
  ILLUMINACLIP:${TRIM_ADAPTERS}:2:30:10 \
  SLIDINGWINDOW:4:20 \
  HEADCROP:5 \
  LEADING:3 \
  TRAILING:3 \
  MINLEN:40

echo "FastQC after Trimmomatic..."
fastqc trimmed/mtb/trimmomatic/*_paired.fastq.gz -o qc_trim/mtb/trimmomatic
multiqc qc_trim/mtb/trimmomatic -o qc_trim/mtb/trimmomatic

"QC + Trimming completed!"

