#!/bin/bash
# Haploid Variant Calling (Single Sample, Line by Line)
# Author: Abaysew

# ------------------------------
# USER INPUT
# ------------------------------
SAMPLE="ERR15418593"
REF="ref_genome/ref.fasta"
VCF_DIR="variants"
mkdir -p "$VCF_DIR"
# ------------------------------

# ------------------------------
# FASTP BAM Variant Calling
# ------------------------------
FASTP_BAM="alignments/mtb/fastp/bam/${SAMPLE}.sorted.dedup.bam"

# Index BAM if needed
samtools index "$FASTP_BAM"

# Index reference if needed
samtools faidx "$REF"

# Call variants
bcftools mpileup -f "$REF" -q 20 -Q 20 -B -Ou "$FASTP_BAM" | \
bcftools call -mv -Ov --ploidy 1 -o "$VCF_DIR/${SAMPLE}.fastp.raw.vcf"

# Filter variants
bcftools filter -i 'QUAL>=30 && DP>=10' -Ov -o "$VCF_DIR/${SAMPLE}.fastp.filtered.vcf" "$VCF_DIR/${SAMPLE}.fastp.raw.vcf"

# Compress filtered VCF
bgzip -c "$VCF_DIR/${SAMPLE}.fastp.filtered.vcf" > "$VCF_DIR/${SAMPLE}.fastp.filtered.vcf.gz"

# Index compressed VCF
bcftools index "$VCF_DIR/${SAMPLE}.fastp.filtered.vcf.gz"


echo "FASTP haploid variant calling completed!"

# ------------------------------
# TRIMMOMATIC BAM Variant Calling
# ------------------------------
TRIM_BAM="alignments/mtb/trimmomatic/bam/${SAMPLE}.sorted.dedup.bam"

# Index BAM if needed
samtools index "$TRIM_BAM"

# Call variants
bcftools mpileup -f "$REF" -q 20 -Q 20 -B -Ou "$TRIM_BAM" | \
bcftools call -mv -Ov --ploidy 1 -o "$VCF_DIR/${SAMPLE}.trimmomatic.raw.vcf"

# Filter variants
bcftools filter -i 'QUAL>=30 && DP>=10' -Ov -o "$VCF_DIR/${SAMPLE}.trimmomatic.filtered.vcf" "$VCF_DIR/${SAMPLE}.trimmomatic.raw.vcf"

# Compress the filtered VCF
bgzip -c "$VCF_DIR/${SAMPLE}.trimmomatic.filtered.vcf" > "$VCF_DIR/${SAMPLE}.trimmomatic.filtered.vcf.gz"

# Index the compressed VCF
bcftools index "$VCF_DIR/${SAMPLE}.trimmomatic.filtered.vcf.gz"


echo "Trimmomatic haploid variant calling completed!"
